HMS-8765: [QE] Content Sources - Test new RBAC RHEL Roles (#560)
* Add two user RBAC test

* Add logInWithReadOnlyUser support

* Apply reviewer's feedback

* fix duplicate test run

* Create and use READONLY_TOKEN

* Add rhel-operator user test

* Add RHEL Operator variables

* Add RHEL_OPERATOR to playwright-actions

* Add RHEL_OPERATOR to nightly

diff --git a/.github/workflows/playwright-actions.yml b/.github/workflows/playwright-actions.yml
--- a/.github/workflows/playwright-actions.yml
+++ b/.github/workflows/playwright-actions.yml
@@ -38,10 +38,34 @@ jobs:
             exit 1
           fi
 
+          if [ -z "$READONLY_USERNAME" ]; then
+            echo "Error: READONLY_USERNAME secret is not set."
+            exit 1
+          fi
+
+          if [ -z "$READONLY_PASSWORD" ]; then
+            echo "Error: READONLY_PASSWORD secret is not set."
+            exit 1
+          fi
+
+          if [ -z "$RHEL_OPERATOR_USERNAME" ]; then
+            echo "Error: RHEL_OPERATOR_USERNAME secret is not set."
+            exit 1
+          fi
+
+          if [ -z "$RHEL_OPERATOR_PASSWORD" ]; then
+            echo "Error: RHEL_OPERATOR_PASSWORD secret is not set."
+            exit 1
+          fi
+
           # Create the .env file and write the secrets and other variables to it
           {
             echo "ADMIN_USERNAME=$ADMIN_USERNAME"
             echo "ADMIN_PASSWORD=$ADMIN_PASSWORD"
+            echo "READONLY_USERNAME=$READONLY_USERNAME"
+            echo "READONLY_PASSWORD=$READONLY_PASSWORD"
+            echo "RHEL_OPERATOR_USERNAME=$RHEL_OPERATOR_USERNAME"
+            echo "RHEL_OPERATOR_PASSWORD=$RHEL_OPERATOR_PASSWORD"
             echo "BASE_URL=https://stage.foo.redhat.com:1337"
             echo "CI=true"
           } >> .env
